version: '3.9'

services:
  mysql-primary:
    image: mysql:latest
    container_name: mysql-primary
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
    ports:
      - "3306:3306"
    command:
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
    networks:
      - mysql-net

  mysql-replica:
    image: mysql:latest
    container_name: mysql-replica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
    ports:
      - "3307:3306"
    command:
      --server-id=2
      --relay-log=relay-bin
      --read-only=1
    depends_on:
      - mysql-primary
    networks:
      - mysql-net

networks:
  mysql-net:
